# Generated by Django 5.2 on 2026-01-24 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('essay', '0001_initial'),
        ('feedback', '0004_alter_nodefeedback_alert_title_and_more'),
        ('map', '0002_remove_map_article_content_remove_map_article_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('action_type', models.CharField(help_text='操作類型', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='操作發生時間')),
                (
                    'metadata',
                    models.JSONField(
                        blank=True, default=dict, help_text='額外的詳細資料（JSON 格式）'
                    ),
                ),
                (
                    'essay',
                    models.ForeignKey(
                        blank=True,
                        help_text='關聯的 Essay',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='user_actions',
                        to='essay.essay',
                    ),
                ),
                (
                    'feedback',
                    models.ForeignKey(
                        blank=True,
                        help_text='關聯的 Feedback',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='user_actions',
                        to='feedback.nodefeedback',
                    ),
                ),
                (
                    'map',
                    models.ForeignKey(
                        blank=True,
                        help_text='關聯的 Map',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='user_actions',
                        to='map.map',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='執行操作的使用者',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='actions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'user_action',
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(
                        fields=['user', '-timestamp'], name='user_action_user_id_672ff4_idx'
                    ),
                    models.Index(fields=['action_type'], name='user_action_action__3f4b4f_idx'),
                    models.Index(fields=['map'], name='user_action_map_id_7f9bfc_idx'),
                ],
            },
        ),
    ]
