# Generated by Django 5.2 on 2026-01-24 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('map', '0002_remove_map_article_content_remove_map_article_topic'),
        ('user_action', '0002_remove_useraction_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='essay',
        ),
        migrations.AlterField(
            model_name='useraction',
            name='map',
            field=models.ForeignKey(
                blank=True,
                help_text='關聯的 Map（Essay 可透過 map.essay 找到）',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='user_actions',
                to='map.map',
            ),
        ),
    ]
