# Generated by Django 5.2 on 2026-01-30 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('essay', '0001_initial'),
        ('map', '0002_remove_map_article_content_remove_map_article_topic'),
        ('user_action', '0003_remove_useraction_essay_alter_useraction_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='essay',
            field=models.ForeignKey(
                blank=True,
                help_text='關聯的 Essay',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='user_actions',
                to='essay.essay',
            ),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='map',
            field=models.ForeignKey(
                blank=True,
                help_text='關聯的 Map',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='user_actions',
                to='map.map',
            ),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['essay'], name='user_action_essay_i_4435de_idx'),
        ),
    ]
