# Generated by Django 5.2 on 2026-01-24 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'group',
                    models.CharField(
                        choices=[('active', 'Active'), ('passive', 'Passive')],
                        default='active',
                        max_length=20,
                        verbose_name='實驗組別',
                    ),
                ),
                (
                    'log',
                    models.JSONField(
                        default=list, help_text='記錄所有組別變更的歷史', verbose_name='變更歷史'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lab',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='用戶',
                    ),
                ),
            ],
            options={
                'verbose_name': '實驗分組',
                'verbose_name_plural': '實驗分組',
                'db_table': 'lab',
            },
        ),
    ]
