# Generated by Django 5.2 on 2026-01-24 09:14

from django.db import migrations
from django.utils import timezone


def create_default_labs(apps, schema_editor):
    """為所有現有用戶建立預設的 Lab 記錄（group='active'）"""
    User = apps.get_model('user', 'User')
    Lab = apps.get_model('lab', 'Lab')

    users_without_lab = User.objects.all()

    labs_to_create = []
    for user in users_without_lab:
        labs_to_create.append(
            Lab(
                user=user,
                group='active',
                log=[
                    {
                        'timestamp': timezone.now().isoformat(),
                        'old_group': None,
                        'new_group': 'active',
                        'changed_by': 'system',
                    }
                ],
            )
        )

    if labs_to_create:
        Lab.objects.bulk_create(labs_to_create)


def reverse_migration(apps, schema_editor):
    """回滾時刪除所有 system 建立的 Lab 記錄"""
    Lab = apps.get_model('lab', 'Lab')
    Lab.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_labs, reverse_migration),
    ]
