# Generated by Django 5.2 on 2025-12-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="map",
            name="article_content",
        ),
        migrations.RemoveField(
            model_name="map",
            name="article_topic",
        ),
    ]
