# Generated by Django 5.2 on 2026-02-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('map', '0002_remove_map_article_content_remove_map_article_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='scoring_remaining',
            field=models.IntegerField(default=5, help_text='心智圖評分剩餘次數'),
        ),
        migrations.AddField(
            model_name='map',
            name='scoring_updated_at',
            field=models.DateTimeField(
                blank=True, help_text='上次評分次數變動時間（供未來重置機制使用）', null=True
            ),
        ),
    ]
