# Generated by Django 5.2 on 2026-03-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('map', '0003_map_scoring_remaining_map_scoring_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='show',
            field=models.BooleanField(
                default=True, help_text='是否顯示在清單中（False 表示已刪除）'
            ),
        ),
    ]
