# Generated by Django 5.2 on 2026-04-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0004_map_show"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[("full", "Full Snapshot"), ("patch", "JSON Patch")], max_length=5
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text='full: {"nodes": [...], "edges": [...]} / patch: [{"op": ..., "path": ..., "value": ...}, ...]'
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(help_text="每個 map 內的自增序號，保證 apply 順序"),
                ),
                (
                    "patches_since_full",
                    models.PositiveIntegerField(
                        help_text="距離上次 full snapshot 累積了幾個 patch"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="map.map",
                    ),
                ),
            ],
            options={
                "db_table": "map_snapshot",
                "ordering": ["sequence"],
                "indexes": [
                    models.Index(fields=["map", "sequence"], name="map_snapsho_map_id_853b51_idx"),
                    models.Index(
                        fields=["map", "snapshot_type"], name="map_snapsho_map_id_ad0185_idx"
                    ),
                ],
            },
        ),
    ]
