# Generated by Django 5.2 on 2025-12-29 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('map', '0002_remove_map_article_content_remove_map_article_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeFeedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('text', models.TextField(help_text='Alert 的 message 內容')),
                ('feedback', models.TextField(blank=True, help_text='LLM 生成的回饋')),
                (
                    'metadata',
                    models.JSONField(
                        default=dict, help_text='操作資訊，例如 {"action": "edit", "node_id": "c1"}'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'map',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='node_feedbacks',
                        to='map.map',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='node_feedbacks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'feedback_nodefeedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
