# Generated by Django 5.2 on 2026-01-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodefeedback',
            name='operation_details',
            field=models.TextField(
                blank=True,
                default='',
                help_text='具體操作描述（例如：學生進行了以下操作：\n1. 編輯了節點 c1）',
            ),
        ),
        migrations.AlterField(
            model_name='nodefeedback',
            name='metadata',
            field=models.JSONField(
                default=dict, help_text='操作資訊 JSON，例如 {"operations": [...]}'
            ),
        ),
        migrations.AlterField(
            model_name='nodefeedback',
            name='text',
            field=models.TextField(help_text='Alert 的 message 內容（例如：完成了 3 個操作）'),
        ),
    ]
