# Generated by Django manually to rename field

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0002_nodefeedback_operation_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodefeedback',
            old_name='text',
            new_name='alert_title',
        ),
    ]
