# Generated by Django 5.2 on 2026-01-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0003_rename_text_nodefeedback_alert_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodefeedback',
            name='alert_title',
            field=models.TextField(help_text='Alert 標題（例如：完成了 3 個操作）'),
        ),
        migrations.AlterField(
            model_name='nodefeedback',
            name='metadata',
            field=models.JSONField(
                default=dict, help_text='操作資訊 JSON（包含詳細的節點內容和變更）'
            ),
        ),
    ]
