# Generated by Django 5.2 on 2026-01-16 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('map', '0002_remove_map_article_content_remove_map_article_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('content', models.TextField(blank=True, default='', help_text='Essay 內容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'map',
                    models.OneToOneField(
                        help_text='關聯的心智圖',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='essay',
                        to='map.map',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='擁有者',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='essays',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'essay',
                'ordering': ['-created_at'],
            },
        ),
    ]
