# Generated by Django 5.2 on 2026-04-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essay", "0002_essay_scoring_remaining_essay_scoring_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="EssaySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(help_text="快照時的完整 Essay 內容")),
                (
                    "sequence",
                    models.PositiveIntegerField(help_text="每個 essay 內的自增序號，保證順序"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="essay.essay",
                    ),
                ),
            ],
            options={
                "db_table": "essay_snapshot",
                "ordering": ["sequence"],
                "indexes": [
                    models.Index(
                        fields=["essay", "sequence"], name="essay_snaps_essay_i_3cbc6c_idx"
                    )
                ],
            },
        ),
    ]
