# Generated by Django 5.2 on 2025-12-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(
                choices=[
                    ('user', 'User'),
                    ('classifier', 'Intent Classifier'),
                    ('operator_support', 'Operator Support'),
                    ('cer_cognitive_support', 'CER Cognitive Support'),
                ],
                max_length=30,
            ),
        ),
    ]
