# Generated by Django 5.2 on 2025-12-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_chatmessage_metadata_alter_chatmessage_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
