# Generated by Django 5.2 on 2026-01-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('assistant', 'Assistant')],
                default='admin',
                max_length=20,
            ),
        ),
    ]
