# Generated by Django 5.2 on 2026-01-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Admin'),
                    ('teacher', 'Teacher'),
                    ('assistant', 'Assistant'),
                    ('student', 'Student'),
                ],
                default='student',
                max_length=20,
            ),
        ),
    ]
