# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindMapTemplate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mindmaptemplate',
            old_name='article_topic',
            new_name='issue_topic',
        ),
    ]
