# Generated by Django 5.2 on 2026-01-20 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mindMapTemplate', '0002_rename_article_topic_to_issue_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmaptemplate',
            name='created_by',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_templates',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name='TemplatePermission',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'assistant',
                    models.ForeignKey(
                        limit_choices_to={'role': 'assistant'},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='template_permissions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'granted_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='granted_template_permissions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'template',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='permissions',
                        to='mindMapTemplate.mindmaptemplate',
                    ),
                ),
            ],
            options={
                'db_table': 'template_permission',
                'ordering': ['-created_at'],
                'unique_together': {('template', 'assistant')},
            },
        ),
    ]
