# Generated by Django 5.2 on 2026-01-20 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mindMapTemplate', '0003_mindmaptemplate_created_by_templatepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindmaptemplate',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_templates',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
