# Generated by Django 5.2 on 2026-01-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mindMapTemplate', '0004_remove_created_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmaptemplate',
            name='end_date',
            field=models.DateTimeField(
                blank=True, help_text='Task closing date and time', null=True
            ),
        ),
        migrations.AddField(
            model_name='mindmaptemplate',
            name='start_date',
            field=models.DateTimeField(
                blank=True, help_text='Task opening date and time', null=True
            ),
        ),
    ]
